cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "internal/db/sqlc"]
exclude_file = []
include_dir = []
exclude_regex = []
include_regex = []
delay = 1000
kill_delay = 500
watch_dirs = ["."]
stop_on_error = true
send_interrupt = false
kill_after = 1000
log_level = "info"
